site_name: Candella Documentation
site_author: Marquis Kurt
site_description: "Candella is a fork of the AliceOS framework for Ren'Py."
docs_dir: docs/

edit_uri: ""

repo_name: 'UnscriptedVN/candella'
repo_url: 'https://github.com/UnscriptedVN/candella'

copyright: 'Copyright &copy; 2021 Unscripted VN Team.'
theme:
  name: null
  custom_dir: 'vanilla/'
  include_search_page: true
  highlightjs: true
  hljs_languages:
    - python
    - json

extra:
    navbar:
      - name: Download
        link: 'https://marquiskurt.itch.io/candella'
      - name: 'GitHub'
        link: "https://github.com/UnscriptedVN/candella"
      - name: 'AppDB'
        link: 'https://appdb.unscriptedvn.dev'
    version:
        provider: mike

plugins:
  - search
  - mike

markdown_extensions:
  - markdown.extensions.admonition
  - meta