name: Build Candella Archive
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - '*'
  release:
    types: [published]


jobs:
  build:
    name: Ren'Py SDK Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-versions:
          - '7.4.1'

    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50 
      - name: Add release tag to Build ID
        shell: bash
        run: |
          ./scripts/version_inject.py
        if: github.event.release
        env:
          tag: ${{ github.ref }}
          sdk: ${{ matrix.renpy-versions }}
      - name: Add build hash to Build ID
        shell: bash
        run: |
          ./scripts/version_inject.py
        if: contains(github.event_name, 'push')
        env:
          commit: ${{ github.sha }}
          sdk: ${{ matrix.renpy-versions }}
      - name: Build Candella archive
        id: buildseq
        uses: ProjectAliceDev/renpy-build-action@v1.1.3
        with:
          sdk-version: ${{ matrix.renpy-versions }}
          project-dir: '.'
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.buildseq.outputs.dir }}
          path: ${{ format('{0}/{1}-System.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}
      - name: Release artifacts to GitHub Release
        uses: skx/github-action-publish-binaries@master
        if: github.event.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ format('{0}/{1}-System.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}
