name: Build Candella Archive (Edge)
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * 2'


jobs:
  build:
    name: Build Edge Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-versions:
          - '7.4.6'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50 
      - name: Add build hash to Build ID
        shell: bash
        run: |
          python3 ./scripts/version_inject.py
        env:
          commit: ${{ github.sha }}
          sdk: ${{ matrix.renpy-versions }}
      - name: Build Candella archive
        id: buildseq
        uses: ProjectAliceDev/renpy-build-action@v1.1.3
        with:
          sdk-version: ${{ matrix.renpy-versions }}
          project-dir: '.'
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.buildseq.outputs.dir }}
          path: ${{ format('{0}/{1}-System.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}
      - name: Upload release to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: framework-edge
          ITCH_GAME: candella
          ITCH_USER: marquiskurt
          VERSION: ${{ github.sha }}
          PACKAGE: ${{ format('{0}/{1}-System.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}
      - name: Upload showcase to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: showcase-edge
          ITCH_GAME: candella
          ITCH_USER: marquiskurt
          VERSION: ${{ github.sha }}
          PACKAGE: ${{ format('{0}/{1}-market.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}
